//@ sourceMappingURL=boxtest.map
// Generated by CoffeeScript 1.6.1
(function() {
  var Map, display;

  display = ROT.Display({
    fontFamily: "DejaVuSansMono, DejaVu Sans Mono, Monaco, Consolas, Inconsolata, monospace",
    fontSize: 21,
    spacing: 1.1,
    width: this.displaywidth,
    height: this.displayheight
  });

  Map = (function() {

    function Map() {}

    Map.prototype.construct = function() {
      resize;      return this.lightPasses = new ArrayBuffer(16);
    };

    return Map;

  })();

  document.body.appendChild(display.getContainer());

}).call(this);
