//@ sourceMappingURL=config.map
// Generated by CoffeeScript 1.6.1
(function() {

  window.constants = {
    lightPasses: 2,
    playerSightRadius: 20,
    playerSpeed: 100,
    hahaSpeedMultipler: 2,
    sprintMeleeMultiplier: 2,
    sprintDistance: 3,
    sprintStepBreathCost: 10,
    meleeBreathCost: 6,
    breathRecoveryStep: 1,
    idleStatusChance: .001,
    selfEsteemColor: '#0000aa',
    imaginationColor: '#880055',
    mirrorImaginationCost: 10
  };

}).call(this);
