//@ sourceMappingURL=gameinit.map
// Generated by CoffeeScript 1.6.1
(function() {
  var onDocumentReady;

  onDocumentReady = function() {
    var seed;
    if ((seed = queryInt('seed')) == null) {
      seed = Date.now();
    }
    ROT.RNG.setSeed(seed);
    return window.game = new Game({
      seed: seed
    });
  };

  Zepto(onDocumentReady);

}).call(this);
