//@ sourceMappingURL=game.map
// Generated by CoffeeScript 1.6.1
(function() {
  'use strict';
  var Game, MAP_DEBUG, SHOW_SEED_URL, StatusMessages, fades, setupRandom;

  MAP_DEBUG = false;

  SHOW_SEED_URL = false;

  fades = [66 / 255, 128 / 255, 255 / 255];

  StatusMessages = (function() {

    StatusMessages.prototype.limit = 3;

    function StatusMessages(node) {
      this.node = node;
      this.messages = [];
    }

    StatusMessages.prototype.addStatus = function(msg) {
      var div, fade, i, node, visibleMessages, _i, _len, _ref, _results;
      this.messages.push({
        text: msg,
        color: [255, 255, 255]
      });
      div = document.createElement('div');
      $(div).html(msg);
      this.node.appendChild(div);
      while (this.node.childNodes.length > this.limit) {
        this.node.removeChild(this.node.childNodes[0]);
      }
      visibleMessages = this.messages.slice(-this.limit);
      _ref = this.node.childNodes;
      _results = [];
      for (i = _i = 0, _len = _ref.length; _i < _len; i = ++_i) {
        node = _ref[i];
        fade = fades[i] != null ? fades[i] : fades[0];
        _results.push(node.setAttribute('style', 'opacity: %s;'.format(fade)));
      }
      return _results;
    };

    return StatusMessages;

  })();

  Game = (function() {

    Game.prototype.display = null;

    Game.prototype.map = {};

    Game.prototype.engine = null;

    Game.prototype.player = null;

    Game.prototype.pedro = null;

    Game.prototype.ananas = null;

    Game.prototype.actors = [];

    function Game() {
      var displayNode, mapDebug;
      setupRandom();
      this.turn = 0;
      this.displaywidth = 50;
      this.displayheight = 25;
      this.statusMessages = new StatusMessages(document.getElementById('status'));
      if (MAP_DEBUG) {
        mapDebug = $("#mapDebug");
        this.debugDisplay = new ROT.Display({
          fontSize: 12
        });
        mapDebug.append(this.debugDisplay.getContainer());
        this.debugDisplayInfo = $("<pre>");
        mapDebug.append(this.debugDisplayInfo);
        this.debugLevels = {};
      }
      this.display = new ROT.Display({
        fontFamily: "Monaco, Consolas, Inconsolata, monospace",
        fontSize: 21,
        spacing: 1.1,
        width: this.displaywidth,
        height: this.displayheight
      });
      displayNode = this.display.getContainer();
      document.getElementById('display').appendChild(displayNode);
      this.engine = new ROT.Engine();
      this.levelDepth = 0;
      this.levels = {};
      this.switchLevel(1, {
        noUpStairs: true
      });
      this.addStatus('You enter the funhouse.');
      this.addStatus('The exit slams shut behind you.');
      this.addStatus('Good luck!');
      this.engine.start();
    }

    Game.prototype.switchLevel = function(delta, opts) {
      var cell, key, needWakeup, x, y, _ref, _ref1, _ref2,
        _this = this;
      this.levelDepth += delta;
      this.level = this.levels[this.levelDepth];
      this.engine.clear();
      needWakeup = false;
      if (this.level == null) {
        if (opts == null) {
          opts = {};
        }
        opts.addActor = function(actor) {
          return _this.engine.addActor(actor);
        };
        opts.removeActor = function(actor) {
          return _this.engine.removeActor(actor);
        };
        opts.depth = this.levelDepth;
        if (this.debugDisplay != null) {
          this.debugLevels[this.levelDepth] = [];
          opts.debugCreate = function(x, y, val) {
            return _this.debugLevels[_this.levelDepth].push([x, y, val]);
          };
        }
        this.level = new Level(this, opts);
        this.levels[this.levelDepth] = this.level;
      } else {
        this.level.wakeUpActors();
      }
      if (this.debugDisplay != null) {
        this.debugDisplay.clear();
        this.debugDisplay.setOptions({
          width: this.level.width,
          height: this.level.height
        });
        _ref = this.level.cells;
        for (key in _ref) {
          cell = _ref[key];
          _ref1 = COORDS(key), x = _ref1[0], y = _ref1[1];
          if (cell && cell.blocksMovement === false) {
            this.debugDisplay.DEBUG(x, y, 1);
          }
        }
        this.debugDisplayInfo.text("Level is " + this.level.width + "x" + this.level.height + " at depth " + this.levelDepth + " with " + this.level.roomInfos.length + " rooms\ndugPercentage: " + this.level.roomDugPercentage + "\nroomRange: " + this.level.roomRange);
      }
      _ref2 = this.level.entryPosition(delta), x = _ref2[0], y = _ref2[1];
      if (this.player == null) {
        this.player = new Player(this.level, x, y);
        this.camera = new Camera(this.player, this.displaywidth, this.displayheight);
      } else {
        this.player.moveToLevel(this.level, x, y);
      }
      this.level.setCamera(this.camera);
      return this.display.clear();
    };

    Game.prototype.addStatus = function(msg) {
      return this.statusMessages.addStatus(msg);
    };

    Game.prototype.updateLegend = function(visibleEntities) {
      var legend;
      legend = document.getElementById('legend');
      return updateLegendNodes(legend, visibleEntities);
    };

    Game.prototype.lock = function() {
      var e;
      this.level.draw();
      this.updateLegend((function() {
        var _i, _len, _ref, _results;
        _ref = this.level.visibleEntities();
        _results = [];
        for (_i = 0, _len = _ref.length; _i < _len; _i++) {
          e = _ref[_i];
          if (!e.entity.hideFromLegend) {
            _results.push(e);
          }
        }
        return _results;
      }).call(this));
      return this.engine.lock();
    };

    Game.prototype.unlock = function() {
      return this.engine.unlock();
    };

    return Game;

  })();

  window.Game = Game;

  setupRandom = function() {
    var seed, url;
    if ((seed = queryInt('seed')) != null) {
      ROT.RNG.setSeed(seed);
    }
    if (SHOW_SEED_URL) {
      url = "http://localhost/?seed=" + ROT.RNG.getSeed();
      return $("#debug").append($("<a>").attr('href', url).text(url));
    }
  };

}).call(this);
