//@ sourceMappingURL=js.map
// Generated by CoffeeScript 1.6.1
(function() {
  var _base, _base1, _base2, _ref, _ref1, _ref2, _ref3;

  if ((_ref = (_base = String.prototype).trim) == null) {
    _base.trim = function() {
      return String(this).replace(/^\s+|\s+$/g, '');
    };
  }

  if ((_ref1 = Math.sign) == null) {
    Math.sign = function(x) {
      if (x > 0) {
        return 1;
      } else if (x < 0) {
        return -1;
      } else {
        return 0;
      }
    };
  }

  if ((_ref2 = (_base1 = Array.prototype).removeRandom) == null) {
    _base1.removeRandom = function() {
      return this.splice(Math.floor(ROT.RNG.getUniform() * this.length), 1)[0];
    };
  }

  if ((_ref3 = (_base2 = Array.prototype).remove) == null) {
    _base2.remove = function(item) {
      var i;
      while ((i = this.indexOf(item)) !== -1) {
        this.splice(i, 1);
      }
    };
  }

}).call(this);
