//@ sourceMappingURL=js.map
// Generated by CoffeeScript 1.6.1
(function() {
  var _base, _ref, _ref1;

  if ((_ref = (_base = String.prototype).trim) == null) {
    _base.trim = function() {
      return String(this).replace(/^\s+|\s+$/g, '');
    };
  }

  if ((_ref1 = Math.sign) == null) {
    Math.sign = function(x) {
      if (x > 0) {
        return 1;
      } else if (x < 0) {
        return -1;
      } else {
        return 0;
      }
    };
  }

}).call(this);
