//@ sourceMappingURL=util.map
// Generated by CoffeeScript 1.6.1
(function() {
  var Point, Rect,
    __slice = [].slice;

  if (console !== void 0 && console.assert !== void 0) {
    window.assert = function() {
      var args;
      args = 1 <= arguments.length ? __slice.call(arguments, 0) : [];
      return console.assert.apply(console, args);
    };
  } else {
    window.assert = function(exp, message) {
      if (!exp) {
        throw message;
      }
    };
  }

  Point = (function() {

    function Point() {}

    Point.distance = function(pt1, pt2) {
      var dx, dy;
      dx = pt2[0] - pt1[0];
      dy = pt2[1] - pt1[1];
      return Math.sqrt(dx * dx + dy * dy);
    };

    return Point;

  })();

  assert(Point.distance([0, 0], [1, 0]) === 1);

  assert(Point.distance([0, 0], [3, 4]) === 5);

  window.Point = Point;

  Rect = (function() {

    function Rect(x1, y1, x2, y2) {
      this.x1 = x1;
      this.y1 = y1;
      this.x2 = x2;
      this.y2 = y2;
    }

    Rect.fromWH = function(x, y, w, h) {
      return new Rect(x, y, x + w, y + h);
    };

    Rect.fromRoom = function(room) {
      return new Rect(room.getLeft(), room.getTop(), room.getRight(), room.getBottom());
    };

    Rect.prototype.center = function() {
      return [this.x1 + (this.x2 - this.x1) / 2, this.y1 + (this.y2 - this.y1) / 2];
    };

    Rect.prototype.containsXY = function(x, y) {
      return x >= this.x1 && x < this.x2 && y >= this.y1 && y < this.y2;
    };

    return Rect;

  })();

  window.Rect = Rect;

  window.isRGB = function(o) {
    return o.length === 3 && typeof o[0] === 'number' && typeof o[1] === 'number' && typeof o[2] === 'number';
  };

  window.clampColor = function(c) {
    var i, _i, _results;
    _results = [];
    for (i = _i = 0; _i <= 2; i = ++_i) {
      _results.push(ROT.Color._clamp(c[i]));
    }
    return _results;
  };

  window.queryString = function(key) {
    var match;
    key = key.replace(/[*+?^$.\[\]{}()|\\\/]/g, "\\$&");
    match = location.search.match(new RegExp("[?&]" + key + "=([^&]+)(&|$)"));
    return match && decodeURIComponent(match[1].replace(/\+/g, " "));
  };

  window.queryInt = function(key) {
    var n, s;
    s = queryString(key);
    if (s != null) {
      n = parseInt(s, 10);
      if (!isNaN(n)) {
        return n;
      }
    }
  };

  window.htmlEntities = function(str) {
    return String(str).replace(/&/g, '&amp;').replace(/</g, '&lt;').replace(/>/g, '&gt;').replace(/"/g, '&quot;');
  };

}).call(this);
